import { Metadata } from "next";

export const metadata: Metadata = {
  title: { absolute: "Free Online CV Builder | Create a Professional Resume in Minutes" },
  description:
    "Build a stunning, ATS-friendly CV in minutes with our free online CV builder. Choose from professional templates, get smart bullet point suggestions, and download as PDF. No signup required to start.",
  keywords: [
    "cv builder",
    "free cv builder",
    "online cv builder",
    "resume builder",
    "free resume builder",
    "professional cv maker",
    "cv template",
    "resume maker online free",
    "ats friendly resume builder",
    "create cv online",
    "cv generator",
    "resume creator",
    "professional resume builder",
    "build cv free",
    "cv maker",
    "resume builder free",
  ],
  openGraph: {
    title: "Free Online CV Builder | Create a Professional Resume in Minutes",
    description:
      "Build a stunning, ATS-optimized CV with smart suggestions. Professional templates, guided step-by-step builder, and instant PDF download. Start free — no signup required.",
    type: "website",
    url: "https://www.rejectly.pro/cv-builder",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "Rejectly AI CV Builder - Create Professional Resumes Free",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Free Online CV Builder — Professional Resume in Minutes",
    description:
      "Build an ATS-friendly CV with smart suggestions. Professional templates, guided builder, instant PDF. Start free.",
    images: ["/og-image.png"],
  },
  alternates: {
    canonical: "https://www.rejectly.pro/cv-builder",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

// JSON-LD Structured Data
const jsonLd = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "Rejectly CV Builder",
  applicationCategory: "BusinessApplication",
  operatingSystem: "Any",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
  },
  description:
    "Free online CV builder that creates professional, ATS-optimized resumes. Features intelligent bullet point suggestions, multiple design themes, and instant PDF export.",
  featureList: [
    "Smart bullet point suggestions",
    "Professional design themes with customizable colors",
    "ATS-optimized formatting",
    "Instant PDF download",
    "Step-by-step guided builder",
    "Auto-detected university locations",
    "Real-time live preview",
  ],
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "Is the CV builder really free?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Yes! You can build your entire CV for free using our step-by-step builder with AI-powered suggestions. Simply create a free account to download your finished CV as a high-quality PDF.",
      },
    },
    {
      "@type": "Question",
      name: "Are the CVs ATS-friendly?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Absolutely. Every CV generated by our builder uses clean, ATS-optimized formatting with proper heading hierarchy, standard fonts, and machine-readable structure. This ensures your resume passes through Applicant Tracking Systems used by 99% of Fortune 500 companies.",
      },
    },
    {
      "@type": "Question",
      name: "How does the AI help me write my CV?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Our AI analyzes your job title and experience to generate tailored, achievement-focused bullet points. It suggests professional summaries, optimizes keyword usage, and ensures your content is compelling and results-oriented.",
      },
    },
    {
      "@type": "Question",
      name: "Can I customize the design of my CV?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Yes! You can choose from multiple professional color themes to match your personal brand. The builder also supports profile photos, custom sections for education, experience, certifications, and skills — all with a modern, clean layout.",
      },
    },
  ],
};

export default function CVBuilderLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      {children}
    </>
  );
}
