import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = 'https://rejectly.pro'

  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/ats-check',
          '/cv-builder',
          '/pricing',
          '/how-it-works',
          '/features',
          '/faq',
          '/about',
          '/contact',
          '/terms',
          '/privacy',
          '/signup',
          '/login',
          '/blog',
          '/blog/*',
          '/resume/*',
          '/favicon.ico',
          '/favicon.svg',
          '/favicon-*.png',
          '/apple-touch-icon.png',
          '/android-chrome-*.png',
          '/og-image.png',
          '/logo.png',
        ],
        disallow: [
          '/dashboard',
          '/dashboard/*',
          '/settings',
          '/settings/*',
          '/billing',
          '/billing/*',
          '/analyze',
          '/analyze/*',
          '/jobs',
          '/jobs/*',
          '/cover-letters',
          '/cover-letters/*',
          '/cv',
          '/cv/*',
          '/reports',
          '/reports/*',
          '/api/',
          '/api/*',
          '/auth/callback',
          '/forgot-password',
          '/reset-password',
          '/_next/',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: [
          '/dashboard',
          '/dashboard/*',
          '/settings',
          '/settings/*',
          '/billing',
          '/billing/*',
          '/analyze',
          '/analyze/*',
          '/jobs',
          '/jobs/*',
          '/cover-letters',
          '/cover-letters/*',
          '/cv',
          '/cv/*',
          '/reports',
          '/reports/*',
          '/api/',
          '/api/*',
          '/auth/callback',
          '/forgot-password',
          '/reset-password',
          '/_next/',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: '/',
        disallow: [
          '/dashboard',
          '/dashboard/*',
          '/settings',
          '/settings/*',
          '/billing',
          '/billing/*',
          '/analyze',
          '/analyze/*',
          '/jobs',
          '/jobs/*',
          '/cover-letters',
          '/cover-letters/*',
          '/cv',
          '/cv/*',
          '/reports',
          '/reports/*',
          '/api/',
          '/api/*',
          '/auth/callback',
          '/forgot-password',
          '/reset-password',
          '/_next/',
        ],
      },
    ],
    sitemap: [
      `${baseUrl}/sitemap.xml`,
      `${baseUrl}/image-sitemap.xml`,
    ],
  }
}
